name: Java Spring Gradle CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run docker compose
        run: docker compose up -d

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '22'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        env:
          DB_HOST: localhost
          DB_NAME: postgres
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          OPENAI_API_KEY: invalid
          OPENAI_API_URL: https://api.openai.com
        run: ./gradlew build


      - name: Test with Gradle
        env:
          DB_HOST: localhost
          DB_NAME: postgres
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          OPENAI_API_KEY: invalid
          OPENAI_API_URL: https://api.openai.com
        run: ./gradlew test
